name: crypto_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.1.0
  - numpy=1.24.3
  - scikit-learn=1.3.0
  - xgboost
  - pip
  - pip:
    - fastapi==0.103.1
    - uvicorn==0.23.2
    - python-dotenv==1.0.0
    - mlflow==2.7.1
    - pytest==7.4.2
    - requests==2.31.0
    - python-binance==1.0.19
    - prometheus-client==0.17.1
    - streamlit==1.27.0
    - plotly==5.17.0
    - ta==0.10.2
  