channels:
- conda-forge
dependencies:
- python=3.9.20
- pip<=24.3.1
- pip:
  - mlflow==2.7.1
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - packaging==23.2
  - pyyaml==6.0.2
  - scikit-learn==1.3.0
  - scipy==1.13.1
name: mlflow-env
